### ISSUE TITLE
Calling `set_range_for_dlp` for G1 only curve gives `Segmentation fault`

### ISSUE THREAD

**Issue by eNipu** [herumi/she-rust#3]
I'm sorry for my limited knowledge about this library and Rust. 

I used `CurveType::SECP256K1`
I was trying to decrypt a large int `i32::MAX`;
```
let lv = i32::MAX;
let c = ppub.enc_g1(lv);
set_try_num(lv as usize);
match sec.dec_g1(&c) {
        Ok(_) => assert!(false),
        Err(err) => assert_eq!(SheError::CantDecrypt, err),
    }
```

The above code decrypts but took about 45milli sec in Linux docker with 4cpu and 2Gb ram. 

Then I tried `set_range_for_dlp(hash_size: usize)` which gives `Segmentation fault`.
The following code blog gives the Segmentation fault.
```
let lv = i32::MAX;
let c = ppub.enc_g1(lv);
set_try_num(lv as usize);
set_range_for_dlp(4);
match sec.dec_g1(&c) {
        Ok(_) => assert!(false),
        Err(err) => assert_eq!(SheError::CantDecrypt, err),
    }
```

Then I also called `set_range_for_g1_dlp(hash_size: usize)` but got `/lib.rs:460: undefined reference to sheSetRangeForG1DLP`

```
let lv = i32::MAX;
let c = ppub.enc_g1(lv);
set_try_num(lv as usize);
set_range_for_g1_dlp(4);
match sec.dec_g1(&c) {
        Ok(_) => assert!(false),
        Err(err) => assert_eq!(SheError::CantDecrypt, err),
    }
```

Please let me know if the problem also happens on your side. 
If not then what is the proper way to call the `set_range_for_g1_dlp` method? 
And how to speed up decryption of large int such as  `i64::MAX`?

**Comment by herumi** [comment]
Thank you for the report.
I've fixed `undefined reference to sheSetRangeForG1DLP` of mcl.
And I've added a sample about DLP to she-rust.
https://github.com/herumi/she-rust/blob/main/examples/large.rs

Could you please update both mcl and she-rust and try it?

Notification
- `set_range_for_g1_dlp(hash_size)` requires about `8 * hash_size` byte.
- `set_try_num(n)` requires O(n) times to decrypt a ciphertext.

So If you want to decrypt a large `Enc(i32::Max)` quickly, then use `hash_size = 1 << 20` and `n = 1 << 11` or so.

**Comment by herumi** [comment]
It takes a long time to `set_range_for_g1_dlp(hash_size)` with large `hash_size`.
So `save_table_for_g1_dlp` and `load_table_for_g1_dlp` can reduce the time.

**Comment by eNipu** [comment]
Thank you so much for the changes and also for implementing `save_table_for_g1_dlp`  and `load_table_for_g1_dlp`.
I've tried on my side and they are working without any problems.

I will close this issue.
 
I have another question related to lifted-ElGamal. I will create a new issue.
